// templates/vue/src/pages/NotFound.vue
<template>
  <div class="min-h-screen bg-gray-50 flex items-center justify-center">
    <div class="text-center px-4">
      <h1 class="text-9xl font-bold text-gray-200">404</h1>
      <h2 class="text-2xl font-semibold text-gray-900 mt-4">Page Not Found</h2>
      <p class="text-gray-600 mt-2 mb-6">
        The page you're looking for doesn't exist or has been moved.
      </p>
      <RouterLink to="/">
        <Button variant="solid">Go to Home</Button>
      </RouterLink>
    </div>
  </div>
</template>

<script setup lang="ts">
import { Button } from "frappe-ui";
</script>

// templates/react/src/pages/NotFound.tsx
import { useNavigate } from "react-router-dom"

export default function NotFound() {
	const navigate = useNavigate()

	return (
		<div className="flex flex-col items-center justify-center min-h-screen gap-4">
			<h1 className="text-6xl font-bold text-gray-300">404</h1>
			<p className="text-gray-500">Página no encontrada</p>
			<button
				type="button"
				onClick={() => navigate("/")}
				className="px-4 py-2 text-sm text-white bg-blue-500 rounded hover:bg-blue-600"
			>
				Volver al inicio
			</button>
		</div>
	)
}
