// templates/react/src/pages/Home.tsx
import { useAuth } from "@/store/auth"

export default function Home() {
	const { user } = useAuth()

	return (
		<div className="flex flex-col items-center justify-center h-full gap-3">
			<span className="text-xs font-medium px-2 py-0.5 rounded-full bg-blue-100 text-blue-700 uppercase tracking-wide">
				React
			</span>
			<h1 className="text-3xl font-bold text-gray-900">{{APP_NAME}}</h1>
			<p className="text-gray-500">Welcome, {user}. Your app is ready. Start building!</p>
		</div>
	)
}

// templates/vue/src/pages/Home.vue
<template>
  <div class="flex items-center justify-center h-full">
    <div class="text-center space-y-3">
      <div class="flex items-center justify-center gap-2">
        <span class="text-xs font-medium px-2 py-0.5 rounded-full bg-green-100 text-green-700 uppercase tracking-wide">Vue</span>
      </div>
      <h1 class="text-3xl font-bold text-gray-900">{{APP_NAME}}</h1>
      <p class="text-gray-500">Your app is ready. Start building!</p>
    </div>
  </div>
</template>

<script setup lang="ts">
// Add your page logic here
</script>
